# Kustomization for tEUR base Kubernetes resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: teur-base

commonLabels:
  app.kubernetes.io/part-of: teur
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespaces/obs-global.yaml
  - network/default-deny.yaml
  - security/pod-security-standards.yaml
